apiVersion: apps/v1
kind: Deployment
metadata:
  name: apple-echo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: apple-echo
  template:
    metadata:
      labels:
        app: apple-echo
    spec:
      containers:
      - name: apple
        image: hashicorp/http-echo
        args:
          - "-text=Apple Service has been invoked via the Nginx Gateway Fabric - Test 4"
        ports:
        - containerPort: 5678
---
apiVersion: v1
kind: Service
metadata:
  name: apple-svc
spec:
  ports:
  - port: 80
    targetPort: 5678
    protocol: TCP
    name: http
  selector:
    app: apple-echo

#---
#apiVersion: gateway.networking.k8s.io/v1
#kind: Gateway
#metadata:
#  name: apple-gateway
#spec:
#  gatewayClassName: nginx
#  listeners:
#  - name: http
#    port: 80
#    protocol: HTTP

---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: apple-route
spec:
  parentRefs:
  - name: gateway
  hostnames:
  - "apple.example.com"
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /
    backendRefs:
    - name: apple-svc
      port: 80

